//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingList.Data.Sql.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopingList
    {
        public System.Guid ShoppingItemId { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid ProductID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
